name: Update Recnet Blog Posts

on:
  push:
    branches:[master]
  schedule:
    - cron: 30 * * * *
    
jobs:
  update:
    run-on:ubuntu-latest
    steps:
      - uses:JasonEto/rss-to-readme@v1
      with:
          feed-url: https://elitedamyth.xyz/feed.xml
          readme-section: feed
